name: nuspell
base: core18
version: '3.1.0'
summary: spell checker
description: |
  Nuspell is a free and open source spell checker library and command-line
  tool. It is designed for languages with rich morphology and complex word
  compounding. Nuspell is a pure C++ implementation supporting Hunspell
  dictionaries.

grade: stable
confinement: strict

parts:
  nuspell:
    plugin: cmake
    configflags:
      - -DBUILD_TESTING=OFF
      - -DBUILD_SHARED_LIBS=ON
    source-type: tar
    source: https://github.com/nuspell/nuspell/archive/v3.1.0.tar.gz
    build-packages:
      - g++
      - cmake
      - libboost-locale-dev
      - libicu-dev
      - ruby-ronn
    stage-packages:
      - libboost-locale1.65.1
      - libicu60
      - hunspell-en-us

apps:
  nuspell:
    command: bin/nuspell
