name: nuspell
base: core18
version: '3.1.2'
summary: spellchecker
description: |
  Nuspell is a fast and safe spelling checker software program. It is designed
  for languages with rich morphology and complex word compounding. Nuspell is
  written in modern C++ and it supports Hunspell dictionaries.

grade: stable
confinement: strict

parts:
  nuspell:
    plugin: cmake
    configflags:
      - -DBUILD_TESTING=OFF
      - -DBUILD_SHARED_LIBS=ON
    source-type: tar
    source: https://github.com/nuspell/nuspell/archive/v3.1.2.tar.gz
    build-packages:
      - g++
      - cmake
      - libboost-locale-dev
      - libicu-dev
      - ruby-ronn
    stage-packages:
      - libboost-locale1.65.1
      - libicu60
      - hunspell-en-us

apps:
  nuspell:
    command: bin/nuspell
