name: nuspell
base: core18
version: '4.0.1'
license: LGPL-3.0
summary: spellchecker
description: |
  Nuspell is a fast and safe spelling checker software program. It is designed
  for languages with rich morphology and complex word compounding. Nuspell is
  written in modern C++ and it supports Hunspell dictionaries.

grade: stable
confinement: strict

plugs:
  hunspell-dictionaries:
    interface: content
    default-provider: hunspell-dictionaries-1-6-1804
    target: $SNAP/usr/share/hunspell

#TODO Add dictionaries installed by apt in /usr/share/hunspell to search.
#
# First approach: /usr/share/hunspell as $SNAP_USER_DATA/.local/share/hunspell
# but $SNAP_USER_DATA is not allowed in layout..bind. (Error in snap doc.)
#
# Second approach: /usr/share/hunspell as $SNAP/usr/share/hunspell which could
# not get working. Complication $SNAP/usr/share/hunspell needed by plug..target.
# Good to try get this working with plug and hunspell-en-us commented out.

parts:
  nuspell:
    plugin: cmake
    configflags:
      - -DBUILD_TESTING=OFF
      - -DCMAKE_BUILD_TYPE=Release
    source-type: tar
    source: https://github.com/nuspell/nuspell/archive/v4.0.1.tar.gz
    build-packages:
      - g++
      - cmake
      - libboost-locale-dev
      - libicu-dev
      - pandoc
    stage-packages:
      - libboost-locale1.65.1
      - libicu60
      - hunspell-en-us

apps:
  nuspell:
    command: bin/nuspell
    plugs:
      - hunspell-dictionaries
    # By default $SNAP_USER_DATA/.local/share/hunspell is also searched.
    environment: # Add $SNAP/usr/share/hunspell to search.
      DICPATH: $SNAP/usr/share/hunspell

