name: nuspell
base: core18
version: '4.0.0'
license: LGPL-3.0
summary: spellchecker
description: |
  Nuspell is a fast and safe spelling checker software program. It is designed
  for languages with rich morphology and complex word compounding. Nuspell is
  written in modern C++ and it supports Hunspell dictionaries.

grade: stable
confinement: strict

# Not yet found by nuspell -D
#plugs:
#  hunspell-dictionaries-plug:
#    interface: content
#    default-provider: hunspell-dictionaries-1-6-1804
#    target: $SNAP/usr/share/hunspell
#    read:
#      - $SNAP/usr/share/hunspell

# Offers /usr/share/hunspell (conflicts with dicts installed with apt and
# duplicates the content of /snap/nuspell/x1/usr/share/hunspell)
#layout:
#  /usr/share/hunspell:
#    bind: $SNAP/usr/share/hunspell

parts:
  nuspell:
    plugin: cmake
    configflags:
      - -DBUILD_TESTING=OFF
      - -DCMAKE_BUILD_TYPE=Release
    source-type: tar
    source: https://github.com/nuspell/nuspell/archive/v4.0.0.tar.gz
    build-packages:
      - g++
      - cmake
      - libboost-locale-dev
      - libicu-dev
      - ruby-ronn
    stage-packages:
      - libboost-locale1.65.1
      - libicu60
      - hunspell-en-us
      - hunspell-da # Installs in /snap/nuspell/x1/usr/share/hunspell (good)

apps:
  nuspell:
    command: bin/nuspell
#    plugs: # see above
#      - hunspell-dictionaries-plug
    environment: # Offers /snap/nuspell/x1/usr/share/hunspell (good)
      DICPATH: $SNAP/usr/share/hunspell

